name: 运行脚本

on:
  push:
    branches:
      - main  # 替换成你的主分支名称

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 替换成你的 Python 版本
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml pandas  # 如果有其他依赖，请添加
    
    - name: 运行 Python 脚本
      run: |
        python script.py  # 替换成你的实际脚本名
        
    - name: 上传文件
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: m3u-playlist
        path: stations.m3u
